re-natal.coffee
Same change as:
https://github.com/dmotz/natal/issues/38
When initializing a project, the .re-natal config file was not created because it "couldn't find device iPhone 6s".
Thanks
=> Default to iPhone 6

re-natal.coffee
As discussed in #22, this command allow re-natal projects that don't have all the re-natal project assumptions to just upgrade figwheel-bridge.js. This allows our upgrade process to be: `npm i re-natal --save-dev && node_modules/.bin/re-natal copy-figwheel-bridge`. Let me know if there's anything I've missed
=> Add copy-figwheel-bridge command - close #22

README.md, re-natal.coffee
Per #26 I've added a use-ios-device command to switch between simulator and a real device. I've verified the repl works for an ios device
@drapanjanas I wanted to QA this on a fresh app but `re-natal init FutureApp` fails for me whether I use master or my branch with:
```
$ node_modules/.bin/re-natal init FutureApp
Creating FutureApp
Creating Leiningen project
Command failed: lein new future-app
```
Is that expected?
=> Use ios device

re-natal.coffee
If you want to debug on the device you have to replace `localhost`
with your ip in `node_modules/react-native/Libraries/WebSocket/RCTWebSocketExecutor.m`.
Yes it is not a joke, edit the react-native library directly as per: [the docs](https://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools)
I added this file to where the url is replaced in AppDelegate.m
=> Updated use-figwheel to replace debug url

re-natal.coffee, resources/cljs-rum/core.cljs, resources/cljs-rum/main_dev.cljs, resources/cljs-rum/main_prod.cljs, resources/cljs-rum/sablono_compiler.clj, resources/cljs-rum/support.cljs
This PR adds [Rum](https://github.com/tonsky/rum) ClojureScript React wrapper support to re-natal.
Rum is an unopinionated React CLJS wrapper:
"Simple, decomplected, isomorphic UI framework for Clojure and ClojureScript".
To generate an application from the Rum template: `re-natal init FutureApp -i rum`
=> Add Rum support

README.md, re-natal.coffee
If a .DS_Store file is created by OS X in the images directory then re-natal will attempt to
require it like any other image file. This causes an error in the simulator as javascript cannot load
the file. As there isnt any reason why a .DS_Store file should be loaded I've added an automatic exclusion for this file name in any part of the image path.
Additions that could be made:
We could expose the exclude list as a configuration in the .re-natal file so that people could see what is being excluded and add to it if needed.
=> Exclude ds store

resources/project.clj
I've added some [Clojurescript compiler options](https://github.com/clojure/clojurescript/wiki/Compiler-Options) for performance. These are normally true under `:advanced` compilation. See `:simple` mode is being used, its better to turn these on.
=> Added some compiler options for performance

resources/cljs-reagent/handlers.cljs, resources/cljs-reagent6/handlers.cljs, resources/project.clj
- `goog.DEBUG` is set to `false` by default in `advanced` optimisation mode. Since we using the `simple` mode, its recommended to set it manually.
- The app should only be checking the schema in development mode and not production mode.
=> Set goog.DEBUG and only check schema in development

README.md
The first time I ran `re-natal init` I waited quite a while, staring at "Creating Leiningen project", before deciding that something had gone wrong. After re-checking all my deps, I tried it again and just left it longer (this is Java after all). Many minutes later, it said "Creating React Native skeleton. Relax, this takes a while..." and my only thought was, "It would have been very reassuring to have been warned about the wait... right from the start"
=> Warn the reader that init takes a while.

resources/project.clj
cljsbuild 1.1.4 requires :builds to be a sequential collection of maps with field :id
=> Updates :builds to be compatible with latest cljsbuild

resources/figwheel-bridge.js, resources/project.clj
Update `lein-figwheel` to latest version 0.5.8. Latest versions of lein-figwheel
generate the "figwheel.connect" including the build id, so I updated
figwheel-bridge to concat the platform id.
=> Update lein-figwheel version

re-natal.coffee
Platform-specific file names for images as described in the React-Native docs at http://facebook.github.io/react-native/releases/0.37/docs/images.html
=> handle platform-specific image files when running use-figwheel

re-natal.coffee
The file which has to be patched for serving *.map files was moved in RN 0.42.0
=> Fix re-natal enable-source-maps

package.json, re-natal.coffee
changes:
- bug fix: writeConfig needs explicit relative path
- cli command: `infer-components` added, calls inferComponents function
- inferComponents method added: parses all cljs files that (presumably) belong to the user, extract calls to `js/require`, compares them to the current config file (verify its integrity first) and if the `modules` entry is different than the infered requires, overwrites them and lets the user know about the differences.
note: platform specific components are not handled yet. I could separate the inferred components based on their path but that is assuming that the `/ios/` `/android/` convention holds which might cause some troubles.
=> Infer components using a regex

README.md
Watchman no longer appears to be optional with the latest version of React Native. Running `react-native start` without Watchman fails with:
```
Loading dependency graph...2017-09-24 10:49 node[25583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
```
=> Include watchman in dependencies

README.md, re-natal.coffee
Add new commands to enable/disable auto-require feature in `use-figwheel` command.
When enabled, `use-figwheel` command will find all the required modules by scanning *.cljs files and generate index.*.js with all correct requires for particular platform.
This feature supposed to make commands `use-component` and `infer-comonents` not needed anymore
=> Auto-require: infer components in use-figwheel command

package.json, re-natal.coffee
- Commands `use-ios-device`, `use-android-device`, `enable-auto-require`, `disable-auto-require` now by default writes into `.re-natal.local` config file.
- Same commands accept `-g` or `--global` option to save configuration in .re-natal file
- Command `use-figwheel` reads configuration from both .re-natal and .re-natal.local files
- fixes #112
=> Support local configuration

resources/cljs-om-next/main_dev.cljs, resources/cljs-reagent/main_dev.cljs, resources/cljs-reagent6/main_dev.cljs, resources/cljs-rum/main_dev.cljs, resources/figwheel-bridge.js
- use only (watch-and-reload ...) way to setup figwheel
- do not explicitly require figwheel.connect.build_${platform} from figwheel-bridge.js
- fixes #143
=> fix double initialization of figwheel

package.json, re-natal.coffee, resources/cljs-om-next/main_dev.cljs, resources/cljs-reagent/main_dev.cljs, resources/cljs-reagent6/main_dev.cljs, resources/cljs-rum/main_dev.cljs, resources/config.cljs
Command `re-natal use-figwheel` will now always regenerate the `env.config` namespace. 
This namespace (which is .gitignored) provides figwheel urls  
fixes #145
fixes #114
=> Move figwheel url configuration into generated namespace

README.md, re-natal.coffee
React Native CLI now generates project with single entry point `index.js`.
Command `re-natal init` now will change corresponding platform files to support separate entry files.
=> Use React Native 0.49

re-natal.coffee, resources/cljs-rum/support.cljs
- fixes #171
- use recent Rum version 0.11.2
- use create-react-class instead of React.createClass in re-natal.support
=> Fix Rum template

README.md
I recently got a little confused following the README instructions for getting Figwheel started after `re-natal init`, so I made some small changes to the instructions that I think clarify the process.
Follow along my misunderstanding: I [asked the question](https://clojurians.slack.com/archives/C0E1SN0NM/p1521787095000184) on clojurians "cljsrn" channel, helpful troubleshooting ensued, and we found a [resolution](https://clojurians.slack.com/archives/C0E1SN0NM/p1521828285000507).
=> README: add instructions for Figwheel from CIDER

re-natal.coffee
The windows team changed the name of the C# class they use to host react native in https://github.com/Microsoft/react-native-windows/commit/395a15695438930d4009ae6c3b34804921f670f2#diff-c94100607ff0edcbee5f94d50acdd06d
=> Updates UWP code generator to use new windows file layout

re-natal.coffee
Fixes so that re-natal may be installed locally in devDependencies, and executed with the `npx` command.
=> Fix so that internal re-natal .cljs files are excluded from require scan

resources/figwheel-bridge.js, resources/project.clj
Context: I upgraded to figwheel 0.5.18 to solve an issue with the clojurescript repl in cider 0.21:
https://github.com/clojure-emacs/cider/issues/2571
Upon doing so, hot reloading broke, but oddly still worked when using an older version of figwheel-bridge.js prior to the changes in https://github.com/drapanjanas/re-natal/pull/185.  I narrowed down the fix to what you see here in this PR, but I'd like to better understand what the underlying issue is, and perhaps there's a better fix that allows us to continue using `importIndexJs`?
This PR also includes the changes in https://github.com/drapanjanas/re-natal/pull/213.
=> Use figwheel 0.5.18
